### PR TITLE
Skip feature handling for databases from unknown vendors

### LINKED ISSUE #24: feature_classes and django-salesforce
[django-salesforce](https://github.com/django-salesforce/django-salesforce) is an ORM integration to the Salesforce API.
It gets set up like any other database source with it's backend identifying as [vendor `salesforce`](https://github.com/django-salesforce/django-salesforce/blob/8ca907ca6b5483f2bc7a5abac772df6d648f9def/salesforce/backend/base.py#L43).

This leads to a KeyError in https://github.com/laymonage/django-jsonfield-backport/blob/56679e1999cd7d20bca1a05e6a9d793830bc72e1/src/django_jsonfield_backport/features.py#L65
because the vendor cannot be found in the `feature_classes` map.

What would be the best way to handle unsupported/unknown database vendors so that I can offer a pull request?

### PR DESCRIPTION
**Pull request by lociii**
Fixes #24

### CODE REVIEW

**Comment by laymonage** [comment]
Hi, thanks for the PR! Could you add a test to cover this? I guess patching one of the databases' `vendor` attribute and asserting that the flags aren't added should be sufficient. If that's asking too much, I can take it from here :slightly_smiling_face:

**Comment by lociii** [comment]
Added tests for static/callable features and unknown vendors.

**Comment by lociii** [comment]
failing 3.9 build is taken care of in #26

**Comment by laymonage** [comment]
@lociii I rebased from `master` and squashed the commits. I also made some edits, but they're pretty minor. Some notes, though:

I changed `assertTrue` and `assertFalse` to `assertIs(..., True)` and `assertIs(..., False)` to avoid incorrectly asserting truthy/falsy values. I caught a bug in the tests: `mock.patch` by default uses `MagicMock`, which is a callable object. When the code checks the feature, it calls the mock and set the `return_value` as the feature value. So, your initial tests actually set the features to be `True` and `lambda: True` (not `True` and `True`). Thus, the callable test fails after I changed the assertion (it previously passed because `lambda: True` is truthy).

I fixed it by using `mock.PropertyMock` in `test_static` and removed the lambda in `test_callable`. I could've added `mock.PropertyMock` and kept the lambda instead, but I think that's not necessary because `MagicMock` (the default) is already a callable object.

Thanks a lot for the PR! I think this is the first time I actually touched `unittest.mock` myself and I learned a lot from it :smile:

**Comment by lociii** [comment]
You're totally right with the boolean assertion. Didn't think of that.
Thanks for improving the tests and publishing the new release.

**Pull request merged**
